### ISSUE TITLE
pageYScroll兼容性

### ISSUE THREAD

**Issue by wufangjian** [ymyang/vue-photoswipe#5]
使用的时候发现在Safari 和  微信里面存在定位问题。 查看源码发现 pageYScroll 有兼容性问题，希望能更新...

bug:

![image](https://user-images.githubusercontent.com/6982055/34189643-76a0384c-e577-11e7-8a38-93525e0759ad.png)

fixed：
```
const pageYScroll = window.pageYOffset    // Safari

     || document.documentElement.scrollTop   //  普遍适用的标准浏览器 chrome  FF...

     || document.body.scrollTop  //  无doctype声明

     || 0
```

**Comment by ymyang** [comment]
thank you!
